library(readr)
library(plyr)
CSI_Inventory <- read_csv("/home/cujo253/2020-03-23_CSI_Inventory.csv")
CSI_Buylist <- read_csv("/home/cujo253/2020-03-23_CSI_Buylist.csv")
CSI_Inventory$`NF/F` <- as.factor(as.character(CSI_Inventory$`NF/F`))
#CSI_Inventory$`NF/F` <- ifelse(is.na(CSI_Inventory$`NF/F`) == T, "", CSI_Inventory$`NF/F` )
Updated_Card_Roster <- read_csv("/home/cujo253/Reports/All_Cards_MB1.csv", col_types = cols(.default = "c"))
Updated_Card_Roster$Semi_Key <- paste(Updated_Card_Roster$name,Updated_Card_Roster$Set, sep = "")
Updated_Card_Roster$`F/NF` <- as.factor(as.character(Updated_Card_Roster$`F/NF`))
Updated_Card_Roster$`F/NF` <- ifelse(is.na(Updated_Card_Roster$`F/NF`) == T, "", as.character(Updated_Card_Roster$`F/NF`))
Updated_Card_Roster$`F/NF` <- as.factor(as.character(Updated_Card_Roster$`F/NF`))
Updated_Card_Roster$Semi_Key <- paste(Updated_Card_Roster$Semi_Key, Updated_Card_Roster$`F/NF`, sep = " ")
#CSI_Inventory$Rarity <- Updated_Card_Roster$Rarity[match(CSI_Inventory$Key,Updated_Card_Roster$Semi_Key)]
#CSI_Inventory$Key <- paste(CSI_Inventory$Key,CSI_Inventory$Rarity,sep="")
#CSI_Inventory$Key <- paste(CSI_Inventory$Key,CSI_Inventory$`NF/F`,sep=" ")
CSI_Inventory$Key <- trimws(CSI_Inventory$Key)
View(CSI_Inventory)
summary(as.factor(CSI_Inventory$Rarity))
CSI_Inventory <- CSI_Inventory[which(as.factor(CSI_Inventory$Conditions) == "NM"),]     
CSI_Inventory$BL <- CSI_Buylist$`Buylist Price`[match(CSI_Inventory$Key,CSI_Buylist$Key)]
CSI_Inventory <- CSI_Inventory[which(is.na(CSI_Inventory$BL)==F),]
#CSI_Inventory<-CSI_Inventory[-8]
CSI_Inventory$Diff <- round(CSI_Inventory$BL/CSI_Inventory$Price,2)
CSI_Inventory <- CSI_Inventory[order(-CSI_Inventory$Diff),]
#Exclusion Sets####
Set_Excl = c("Throne of Eldraine",
             "Modern Horizons",
             "War of the Spark",
             "Core Set 2020",
             "Amonkhet",
             "Ravnica Allegiance",
             "2015 Core Set",
             "Dominaria",
             "2014 Core Set",
             "Commander 2019",
             "Guilds of Ravnica",
             "Khans of Tarkir",
             "Aether Revolt",
             "Theros",
             "Ixalan",
             "Kaladesh",
             "Fate Reforged",
             "Core Set 2019",
             "Unstable",
             "Return to Ravnica",
             "Rivals of Ixalan",
             "2013 Core Set",
             "Hour of Devastation",
             "Duel Decks: Elves Vs. Inventors",
             "Shadows Over Innistrad",
             "Eldritch Moon",
             "2011 Core Set",
             "Zendikar",
             "Future Sight",
             "Born of the Gods",
             "Ultimate Masters",
             "Iconic Masters",
             "Explorers of Ixalan",
             "Magic Origins",
             "Prophecy",
             "Dragons of Tarkir",
             "Dragon's Maze",
             "Gatecrash",
             "Innistrad",
             "Battle for Zendikar",
             "Ice Age",
             "Modern Masters 2015",
             "Chronicles",
             "Fifth Dawn",
             "Oath of the Gatewatch",
             "Champions of Kamigawa",
             "Journey into Nyx",
             "Commander 2018",
             "Worldwake",
             "Avacyn Restored",
             "New Phyrexia",
             "Commander 2014",
             "Dark Ascension",
             "Tempest",
             "Dissension",
             "2012 Core Set",
             "Battlebond",
             "Guildpact",
             "Commander 2017",
             "Time Spiral",
             "Visions",
             "Ravnica",
             "Masters 25",
             "Darksteel",
             "Shadowmoor",
             "Signature Spellbook: Gideon",
             "Scars of Mirrodin",
             "Rise of the Eldrazi",
             "Coldsnap",
             "Urza's Legacy",
             "Odyssey",
             "Legions",
             "Urza's Saga",
             "Mirrodin",
             "Global Series: Jiang Yanggu & Mu Yanling",
             "2010 Core Set",
             "Planar Chaos",
             "Mirrodin Besieged",
             "Morningtide",
             "Conspiracy",
             "Invasion",
             "Modern Masters 2017",
             "Conspiracy - Take the Crown",
             "Onslaught",
             "Conflux",
             "Eternal Masters",
             "Saviors of Kamigawa",
             "Torment",
             "Stronghold",
             "Planeshift",
             "Commander 2013",
             "Weatherlight",
             "Commander 2016",
             "Scourge",
             "Mirage",
             "Modern Masters",
             "Nemesis",
             "Unlimited",
             "Lorwyn",
             "Apocalypse",
             "Mercadian Masques",
             "Exodus",
             "Alara Reborn",
             "Betrayers of Kamigawa",
             "Urza's Destiny",
             "Legends",
             "Modern Event Deck",
             "Alliances",
             "Duel Decks: Mind Vs. Might",
             "Commander Anthology Vol. II",
             "Ravnica Allegiance: Guild Kits",
             "Commander",
             "Commander 2015",
             "Signature Spellbook: Jace",
             "Duel Decks: Zendikar Vs. Eldrazi",
             "Duel Decks: Nissa Vs. Ob Nixilis",
             "Homelands",
             "Duel Decks: Izzet Vs. Golgari",
             "Eventide",
             "The Dark",
             "Duel Decks: Blessed Vs. Cursed",
             "Chronicles",
             "Judgment",
             "Weatherlight",
             "Ice Age",
             "Duel Decks: Jace Vs. Vraska",
             "Planechase Anthology",
             "Fallen Empires",
             "10th Edition",
             "Duel Decks: Sorin Vs. Tibalt",
             "Archenemy - Nicol Bolas",
             "Antiquities",
             "Time Spiral",
             "Duel Decks: Speed Vs. Cunning",
             "Duel Decks: Knights Vs. Dragons",
             "Commander Anthology",
             "Duel Decks: Venser Vs. Koth",
             "Duel Decks: Elspeth Vs. Tezzeret",
             "Game Night",
             "Duel Decks: Elspeth Vs. Kiora",
             "Tempest",
             "Unglued",
             "Scourge",
             "Duel Decks: Heroes Vs. Monsters",
             "Portal",
             "Torment",
             "Fallen Empires",
             "Legions",
             "Stronghold",
             "Unhinged",
             "Shards of Alara",
             "3rd Edition",
             "Guilds of Ravnica: Guild Kits",
             "Nemesis",
             "Portal",
             "Odyssey",
             "Coldsnap",
             "7th Edition",
             "Urza's Saga",
             "Duel Decks: Jace Vs. Chandra",
             "Planechase 2012",
             "Archenemy",
             "6th Edition",
             "Duel Decks: Merfolk Vs. Goblins",
             "Duel Decks: Garruk Vs. Liliana",
             "Urza's Legacy",
             "Duel Decks: Phyrexia Vs. The Coalition",
             "Portal II",
             "5th Edition",
             "Onslaught",
             "Timeshifted",
             "4th Edition",
             "Legends",
             "Beatdown",
             "8th Edition",
             "Antiquities",
             "Prophecy",
             "Mercadian Masques",
             "Planechase",
             "Timeshifted",
             "Duel Decks: Ajani Vs. Nicol Bolas",
             "Duel Decks: Elves Vs. Goblins",
             "Mirage",
             "Battle Royale",
             "Duel Decks: Divine Vs. Demonic",
             "The Dark",
             "Starter 1999",
             "Apocalypse",
             "Starter 1999",
             "Urza's Destiny",
             "Homelands",
             "Portal 3K",
             "Battle Royale",
             "Starter 2000",
             "Visions",
             "Portal 3K",
             "Arabian Nights",
             "Portal II",
             "Unlimited",
             "Beta",
             "Beta",
             "Alpha",
             "Alpha",
             "World Championships",
             "Throne of Eldraine Variants",
             "Promotional",
             "Duel Decks: Anthology",
             "Anthologies",
             "Promo Pack",
             "Collectors Ed",
             "Magic Origins",
             "Conflux",
             "Journey into Nyx",
             "Commander 2019",
             "Ixalan",
             "Born of the Gods",
             "Rise of the Eldrazi",
             "Commander",
             "Amonkhet",
             "Return to Ravnica",
             "Avacyn Restored",
             "Innistrad",
             "Ravnica Allegiance",
             "Shadows Over Innistrad",
             "Dark Ascension",
             "Oath of the Gatewatch",
             "2014 Core Set",
             "Core Set 2019",
             "Dragons of Tarkir",
             "Dragon's Maze",
             "Dominaria",
             "Throne of Eldraine Variants",
             "Gatecrash",
             "Modern Masters 2015",
             "Unstable",
             "2012 Core Set",
             "2010 Core Set",
             "Commander 2014",
             "Iconic Masters",
             "Alara Reborn",
             "Guilds of Ravnica: Guild Kits",
             "Hour of Devastation",
             "Shards of Alara",
             "Modern Masters 2017",
             "Battle for Zendikar",
             "Ravnica Allegiance: Guild Kits",
             "Unstable",
             "Iconic Masters",
             "Khans of Tarkir",
             "2011 Core Set",
             "Promo Pack",
             "Promo Pack",
             "Commander 2018",
             "2012 Core Set",
             "Zendikar",
             "Worldwake",
             "Commander 2013",
             "Throne of Eldraine",
             "Signature Spellbook: Gideon",
             "6th Edition",
             "3rd Edition",
             "8th Edition",
             "7th Edition",
             "5th Edition",
             "9th Edition",
             "Collectors Ed Intl",
             "4th Edition",
             "Fate Reforged",
             "Judgment",
             "Onslaught",
             "Collectors Ed",
             "Collectors Ed Intl",
             "Alliances",
             "Collectors Ed",
             "Beta",
             "Exodus",
             "Anthologies",
             "Coldsnap Theme Decks",
             "3rd Edition",
             "5th Edition",
             "Mirage",
             "Unlimited",
             "6th Edition",
             "Tempest",
             "Urza's Legacy",
             "7th Edition",
             "Anthologies",
             "Antiquities",
             "Arabian Nights",
             "Coldsnap",
             "Collectors Ed Intl",
             "Beatdown",
             "Time Spiral",
             "Prophecy",
             "Legends",
             "Mercadian Masques",
             "Urza's Saga",
             "Coldsnap Theme Decks",
             "Starter 1999",
             "Urza's Destiny",
             "Nemesis",
             "Scourge",
             "Judgment",
             "Odyssey",
             "Starter 2000",
             "Torment",
             "Vanguard",
             "Vanguard",
             "Ice Age",
             "Game Night",
             "Eldritch Moon",
             "Scars of Mirrodin",
             "Throne of Eldraine Variants",
             "2015 Core Set",
             "Gatecrash",
             "Kaladesh",
             "War of the Spark",
             "Aether Revolt",
             "Rivals of Ixalan",
             "Core Set 2020",
             "Theros",
             "Guilds of Ravnica",
             "Journey into Nyx",
             "Ravnica Allegiance: Guild Kits",
             "Explorers of Ixalan",
             "Core Set 2020",
             "2015 Core Set",
             "Battle for Zendikar",
             "Explorers of Ixalan",
             "War of the Spark",
             "Ravnica Allegiance",
             "Ravnica",
             "Future Sight",
             "World Championships",
             "9th Edition",
             "8th Edition",
             "Promotional",
             "Commander 2017",
             "Commander 2015",
             "Commander Anthology Vol. II",
             "Champions of Kamigawa",
             "Planechase",
             "Unhinged",
             "Unglued",
             "Invasion",
             "10th Edition",
             "Planeshift",
             "Mirrodin",
             "Battlebond",
             "Duel Decks: Merfolk Vs. Goblins",
             "New Phyrexia",
             "Ultimate Masters",
             "Commander Anthology",
             "Duel Decks: Elves Vs. Goblins",
             "Duel Decks: Merfolk Vs. Goblins",
             "Duel Decks: Jace Vs. Vraska",
             "Duel Decks: Elves Vs. Inventors",
             "Shadowmoor",
             "Planechase Anthology",
             "Lorwyn",
             "Modern Masters",
             "Morningtide",
             "Commander 2016",
             "Guildpact",
             "Eventide",
             "Duel Decks: Nissa Vs. Ob Nixilis",
             "Duel Decks: Garruk Vs. Liliana",
             "Duel Decks: Mind Vs. Might",
             "Fifth Dawn",
             "Saviors of Kamigawa",
             "Avacyn Restored",
             "Planar Chaos",
             "Deckmaster",
             "Duel Decks: Izzet Vs. Golgari",
             "Masters 25",
             "Champions of Kamigawa",
             "Commander 2014",
             "2013 Core Set",
             "Conflux",
             "Duel Decks: Venser Vs. Koth",
             "Planar Chaos",
             "Archenemy",
             "Signature Spellbook: Jace",
             "Conspiracy",
             "Duels of the Planeswalkers",
             "Duel Decks: Elspeth Vs. Kiora",
             "Darksteel",
             "Duel Decks: Blessed Vs. Cursed",
             "Battle Royale",
             "Betrayers of Kamigawa",
             "Modern Masters",
             "Eternal Masters",
             "Duel Decks: Nissa Vs. Ob Nixilis",
             "Conspiracy - Take the Crown",
             "Duel Decks: Ajani Vs. Nicol Bolas",
             "Duel Decks: Anthology",
             "Fallen Empires",
             "Darksteel",
             "Mirrodin Besieged",
             "Planechase",
             "Unglued",
             "Commander Anthology Vol. II",
             "2011 Core Set",
             "Duel Decks: Speed Vs. Cunning",
             "Duel Decks: Phyrexia Vs. The Coalition",
             "Legions",
             "Archenemy - Nicol Bolas",
             "Commander 2018",
             "Global Series: Jiang Yanggu & Mu Yanling",
             "Dark Ascension",
             "Unhinged",
             "Promotional",
             "World Championships",
             "Planechase 2012",
             "2010 Core Set",
             "Archenemy",
             "Duel Decks: Divine Vs. Demonic",
             "Duel Decks: Jace Vs. Chandra",
             "Duel Decks: Sorin Vs. Tibalt",
             "Duel Decks: Elspeth Vs. Tezzeret",
             "Duel Decks: Knights Vs. Dragons",
             "Commander 2015",
             "Legions",
             "Masters 25",
             "Dissension",
             "Rise of the Eldrazi",
             "Modern Event Deck",
             "Commander",
             "Commander 2013",
             "Duel Decks: Heroes Vs. Monsters",
             "Eventide",
             "Magic Origins",
             "Modern Horizons",
             "Deckmaster",
             "Duel Decks: Mind Vs. Might",
             "Duel Decks: Zendikar Vs. Eldrazi",
             "Amonkhet",
             "Ravnica",
             "Shadowmoor",
             "Shadows Over Innistrad",
             "Throne of Eldraine",
             "Masterpiece Series: Mythic Edition",
             "Ultimate Masters",
             "10th Edition",
             "Art Series",
             "Hour of Devastation",
             "Invasion",
             "Shards of Alara",
             "Duel Decks: Blessed Vs. Cursed",
             "War of the Spark JPN Planeswalkers",
             "Planechase Anthology",
             "Duel Decks: Jace Vs. Chandra",
             "Aether Revolt",
             "Duel Decks: Zendikar Vs. Eldrazi",
             "Commander Anthology",
             "Commander 2016",
             "Duel Decks: Ajani Vs. Nicol Bolas",
             "Duel Decks: Izzet Vs. Golgari",
             "Duels of the Planeswalkers",
             "8th Edition",
             "The Dark",
             "Arabian Nights",
             "Invasion",
             "Portal II",
             "Weatherlight",
             "Alpha",
             "Timeshifted",
             "World Championships",
             "Deckmaster",
             "War of the Spark JPN Planeswalkers",
             "Masterpiece Series: Mythic Edition",
             "Vanguard",
             "Apocalypse",
             "Theros Beyond Death",
             "Mystery Booster")
Excl_Excl <- c("Standard",
               "Modern",
               "Standard",
               "Standard",
               "Pioneer",
               "Standard",
               "Pioneer",
               "Pioneer",
               "Pioneer",
               "EDH",
               "Standard",
               "Pioneer",
               "Pioneer",
               "Pioneer",
               "Pioneer",
               "Pioneer",
               "Exclude",
               "Pioneer",
               "Unclear",
               "Pioneer",
               "Pioneer",
               "Modern",
               "Pioneer",
               "Unclear",
               "Pioneer",
               "Pioneer",
               "Modern",
               "Modern",
               "Modern",
               "Pioneer",
               "Modern",
               "EDH",
               "Pioneer",
               "Pioneer",
               "Exclude",
               "Pioneer",
               "Pioneer",
               "Pioneer",
               "Modern",
               "Pioneer",
               "Exclude",
               "Modern",
               "Exclude",
               "Modern",
               "Pioneer",
               "Modern",
               "Pioneer",
               "EDH",
               "Modern",
               "Modern",
               "Modern",
               "EDH",
               "Modern",
               "Exclude",
               "Modern",
               "Modern",
               "EDH",
               "Modern",
               "EDH",
               "Exclude",
               "Exclude",
               "Modern",
               "Modern",
               "Modern",
               "Modern",
               "EDH",
               "Modern",
               "Modern",
               "Exclude",
               "Exclude",
               "Exclude",
               "Unclear",
               "Exclude",
               "Modern",
               "EDH",
               "Modern",
               "Modern",
               "Modern",
               "Modern",
               "EDH",
               "Unclear",
               "Modern",
               "EDH",
               "Exclude",
               "EDH",
               "EDH",
               "Modern",
               "Exclude",
               "Exclude",
               "EDH",
               "EDH",
               "Exclude",
               "EDH",
               "Exclude",
               "Exclude",
               "Modern",
               "Exclude",
               "Exclude",
               "Modern",
               "Exclude",
               "Exclude",
               "Exclude",
               "Modern",
               "Modern",
               "Exclude",
               "Exclude",
               "Unclear",
               "Exclude",
               "Unclear",
               "EDH",
               "Pioneer",
               "EDH",
               "EDH",
               "EDH",
               "Unclear",
               "Unclear",
               "Exclude",
               "Unclear",
               "Modern",
               "Exclude",
               "Unclear",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Unclear",
               "EDH",
               "Unclear",
               "Modern",
               "Unclear",
               "EDH",
               "Exclude",
               "Exclude",
               "Unclear",
               "Unclear",
               "EDH",
               "Unclear",
               "Unclear",
               "Exclude",
               "Unclear",
               "Exclude",
               "Unclear",
               "Exclude",
               "Unclear",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Unclear",
               "Modern",
               "Exclude",
               "EDH",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Unclear",
               "EDH",
               "EDH",
               "Exclude",
               "Unclear",
               "Unclear",
               "Exclude",
               "Unclear",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "EDH",
               "Exclude",
               "Unclear",
               "Unclear",
               "Exclude",
               "Unclear",
               "Unclear",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Unclear",
               "Standard",
               "EDH",
               "Unclear",
               "Exclude",
               "EDH",
               "Exclude",
               "Pioneer",
               "EDH",
               "Pioneer",
               "EDH",
               "Pioneer",
               "Pioneer",
               "Modern",
               "EDH",
               "Pioneer",
               "Pioneer",
               "Modern",
               "Modern",
               "Standard",
               "Pioneer",
               "Modern",
               "Pioneer",
               "Pioneer",
               "Pioneer",
               "Pioneer",
               "Pioneer",
               "Pioneer",
               "Standard",
               "Pioneer",
               "Modern",
               "Unclear",
               "Modern",
               "Modern",
               "EDH",
               "EDH",
               "Modern",
               "EDH",
               "Pioneer",
               "Modern",
               "Modern",
               "Pioneer",
               "Pioneer",
               "Unclear",
               "EDH",
               "Pioneer",
               "Modern",
               "EDH",
               "EDH",
               "EDH",
               "Modern",
               "Modern",
               "Modern",
               "EDH",
               "Standard",
               "EDH",
               "Exclude",
               "Exclude",
               "Modern",
               "Exclude",
               "Exclude",
               "Modern",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Pioneer",
               "Modern",
               "Standard",
               "Pioneer",
               "Pioneer",
               "Pioneer",
               "Standard",
               "Pioneer",
               "Pioneer",
               "Standard",
               "Pioneer",
               "Standard",
               "Pioneer",
               "Pioneer",
               "Pioneer",
               "Standard",
               "Pioneer",
               "Pioneer",
               "Pioneer",
               "Standard",
               "Standard",
               "Modern",
               "Modern",
               "Unclear",
               "Modern",
               "Modern",
               "EDH",
               "EDH",
               "EDH",
               "EDH",
               "Modern",
               "EDH",
               "Unclear",
               "Unclear",
               "Unclear",
               "Modern",
               "EDH",
               "Modern",
               "EDH",
               "Unclear",
               "Modern",
               "Modern",
               "EDH",
               "Unclear",
               "Unclear",
               "Unclear",
               "Unclear",
               "Modern",
               "EDH",
               "Modern",
               "Modern",
               "Modern",
               "EDH",
               "Modern",
               "Modern",
               "Unclear",
               "Unclear",
               "Unclear",
               "Modern",
               "Modern",
               "Modern",
               "Modern",
               "Unclear",
               "Unclear",
               "Modern",
               "Modern",
               "EDH",
               "Modern",
               "EDH",
               "Unclear",
               "Modern",
               "EDH",
               "EDH",
               "EDH",
               "Unclear",
               "Unclear",
               "Modern",
               "Unclear",
               "Unclear",
               "Modern",
               "Modern",
               "EDH",
               "Unclear",
               "EDH",
               "Unclear",
               "Unclear",
               "Unclear",
               "Modern",
               "Modern",
               "EDH",
               "Unclear",
               "EDH",
               "Modern",
               "Unclear",
               "Unclear",
               "Unclear",
               "EDH",
               "EDH",
               "EDH",
               "Modern",
               "Unclear",
               "EDH",
               "Unclear",
               "EDH",
               "Modern",
               "EDH",
               "Unclear",
               "Unclear",
               "Unclear",
               "Unclear",
               "Unclear",
               "EDH",
               "Unclear",
               "Modern",
               "Modern",
               "Modern",
               "Unclear",
               "EDH",
               "EDH",
               "Unclear",
               "Modern",
               "Pioneer",
               "Modern",
               "Unclear",
               "Unclear",
               "Unclear",
               "Pioneer",
               "Modern",
               "Modern",
               "Pioneer",
               "Standard",
               "EDH",
               "Modern",
               "Modern",
               "Unclear",
               "Pioneer",
               "Unclear",
               "Modern",
               "Unclear",
               "Standard",
               "EDH",
               "Unclear",
               "Pioneer",
               "Unclear",
               "EDH",
               "EDH",
               "Unclear",
               "Unclear",
               "Unclear",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Exclude",
               "Standard",
               "EDH",
               "Exclude",
               "Exclude",
               "Standard",
               "Unclear")
Exclusion <- data.frame(Set_Excl,Excl_Excl, stringsAsFactors = TRUE)

##Anywho####
CSI_Inventory$Exclude <- Exclusion$Excl_Excl[match(CSI_Inventory$`Card Set`,Exclusion$Set_Excl)]
CSI_Inventory <- CSI_Inventory[which(CSI_Inventory$Exclude != "Exclude"),]
CSI_Inventory <- CSI_Inventory[which(CSI_Inventory$Diff < 1.00),]
CSI_EDH <- CSI_Inventory[which(CSI_Inventory$Exclude == "EDH"),]
CSI_Modern <- CSI_Inventory[which(CSI_Inventory$Exclude == "Modern"),]
CSI_Pioneer <- CSI_Inventory[which(CSI_Inventory$Exclude == "Pioneer"),]
CSI_Standard <- CSI_Inventory[which(CSI_Inventory$Exclude == "Standard"),]
summary(CSI_EDH$Diff)
summary(CSI_Modern$Diff)
summary(CSI_Pioneer$Diff)
summary(CSI_Standard$Diff)
round(mean(CSI_EDH$Diff),2)
round(mean(CSI_Modern$Diff),2)
round(mean(CSI_Pioneer$Diff),2)
round(mean(CSI_Standard$Diff),2)
round(median(CSI_EDH$Diff),2)
round(median(CSI_Modern$Diff),2)
round(median(CSI_Pioneer$Diff),2)
round(median(CSI_Standard$Diff),2)
