#!/bin/bash
clear
echo "The Beacons are Being Lit!"
echo "Reports Have Been Sent!"
rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/Reports/ 167.172.233.212:/home/cujo253/Reports/

rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/Reports/ 64.225.20.203:/home/cujo253/Reports/




echo "Counting the Uruk-Hai..."
rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/Metrics/ 167.172.233.212:/home/cujo253/Metrics/

rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/Metrics/ 167.99.63.23:/home/cujo253/Metrics/




echo "Mustering the Rohirrim ..."
rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/cronR/ 167.172.233.212:/home/cujo253/cronR/

rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/cronR/ 64.225.20.203:/home/cujo253/cronR/

rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/cronR/ 167.99.63.23:/home/cujo253/cronR/



echo "Honouring our Allegiance..."
rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/'Funny Money'/ 167.172.233.212:/home/cujo253/'Funny Money'/


echo "Enjoying the Fabled Hospitality..."
rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/Essential_Referential_CSVS/ 167.172.233.212:/home/cujo253/Essential_Referential_CSVS/

rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/Essential_Referential_CSVS/ 64.225.20.203:/home/cujo253/Essential_Referential_CSVS/

rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/Essential_Referential_CSVS/ 167.99.63.23:/home/cujo253/Essential_Referential_CSVS/



echo "Consulting the White Wizard..."
rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/'Current Scripts'/ 167.172.233.212:/home/cujo253/Current/

rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/'Current Scripts'/ 64.225.20.203:/home/cujo253/Current/

rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/'Current Scripts'/ 167.99.63.23:/home/cujo253/Current/



echo "Not Letting the White City Burn..."
rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/CEI_Work/ 167.172.233.212:/home/cujo253/CEI_Work/

rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/CEI_Work/ 64.225.20.203:/home/cujo253/CEI_Work/

rsync -e 'sshpass -p "brodeur95" ssh -p 253' -avz /home/cujo253/CEI_Work/ 167.99.63.23:/home/cujo253/CEI_Work/

echo "------------------------------------"
echo "----Theoden king stands alone...----"
echo "--------Not alone. Rohirrim!--------"
echo "------------------------------------"


